### ISSUE TITLE
No demo usernames nor password

### ISSUE THREAD

**Issue by Benoit1980** [Taskana/taskana#2125]
Hello,

I wanted to try your app but there are no demo username nor password on your page.

Thanks!

Ben

**Comment by arolfes** [comment]
Hi @Benoit1980 ,

the URL is https://taskana.mybluemix.net/taskana/

If you want test the app as admin user use the classical admin admin combination.

If you want to explore our demo as a non-admin you can also login as any of our test users. The password is always the username.
Here you can find our documentation about our current test users: https://taskana.atlassian.net/wiki/spaces/TAS/pages/1150189569/Test+User+Structure

I hope it helps.

Best Regards
Alex

**Comment by mustaphazorgati** [comment]
Hey @Benoit1980!

Just a quick disclaimer: Our demo app is part in a POC state. 
Currently only the administrative panel is production ready. 
Typically, the workplace and the monitoring frontend's are implemented by our users in order to keep TASKANA behind a corporate design. Therefore our demo app only shows a fraction of TASKANA's functionality.

Instead our REST Service show's almost the entire functionality of TASKANA (some functions only exist in the Java API. We're working on that, so that the REST Service and the Java API are functionally identical soon). Have a look at our REST Service documentation: https://taskana.mybluemix.net/taskana/docs/rest/rest-api.html

Furthermore we offer a free (60-90 min) introduction session to TASKANA where we showcase the issue we want to solve, how we solve it, get a feel for your usecase and possible can discuss further cooperation ;) Feel free to reach out to me if you're interested: mustapha.zorgati@novatec-gmbh.de
