### ISSUE TITLE
Update the list in the PR desciption, so that the todos are up to date

### ISSUE THREAD

**Issue by ryzheboka** [Taskana/taskana#2446]
Some todos are not done anymore (e. g. check bluemix environment). We should discuss them. If they are not relevant, they should be removed from the list. If they are relvant, we should decide in which case they are relevant. We should also add a link to out GithubIssues Board.
Our problem right now is that we tend to forget to move tickets to their correct stages. This should be more obvious from the todo list.

**Comment by arolfes** [comment]
Hello @ryzheboka , yes you are right, please let us discuss them in the meeting today :)

**Comment by arolfes** [comment]
my 2 cents to the bluemix environment

it's not bluemix anymore because IBM stopped the free tier subscription, so we switched to azure
My personal oppion: this should be an automated task
for the beginning a simple curl check and a curl login is fine I think,
later it can be done via selenium or something
